[package]
name = "sevenz-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "2.1"
bit-set = "0.5.3"
lzma-rs = "0.2"