[package]
name = "sevenz-rust"
version = "0.1.2"
edition = "2021"
readme = "README.md"
homepage = "https://github.com/dyz1990/sevenz-rust"
repository = "https://github.com/dyz1990/sevenz-rust"
license = "Apache-2.0"
keywords=["7z","7zip","sevenz","decompress"]
description = "A 7z decompressor written in pure rust"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
bit-set = "0.5.3"
lzma-rs = "0.2"

[dev-dependencies]
tempfile = "3.3.0"
